### PR TITLE
Fix testing by tidying and vendoring files

### PR DESCRIPTION
**Pull request by c1728p9**
Fix tests.sh by running the below commands and committing the results:
```
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Review by costanic — CHANGES_REQUESTED** [review]
Please do not add the websocket library back into the repo.  It was previously deleted on purpose because it caused confusion and at least one bug: https://github.com/PelionIoT/edge-proxy/pull/10/commits/53c494d6cb84e55eac3dafe2ae967ee7c75bdc09

**Comment by costanic** [comment]
Also, we are not using that version of websocket, we are using a specially patched fork as can be seen here: https://github.com/PelionIoT/edge-proxy/blob/7e70a2f1cc32e7cd732d5abfa41857da017abb24/go.mod#L16

**Comment by c1728p9** [comment]
@costanic thanks for the prompt review. This PR copies files from https://github.com/pelioniot/websocket at v1.4.2-1 into the vendor directory of this repository. It isn't bringing in the standard gorilla websocket library. Do you anticipate this causing issues, or is this the version it should be using?

**Comment by costanic** [comment]
> @costanic thanks for the prompt review. This PR copies files from https://github.com/pelioniot/websocket at v1.4.2-1 into the vendor directory of this repository. It isn't bringing in the standard gorilla websocket library. Do you anticipate this causing issues, or is this the version it should be using?

ah ok, that's good.  I was confused by the path of the new files.  The pelioniot fork is indeed required for correct functionality.

Could you explain why we need to copy the websocket source into this repo now that we have Go modules?  My strong preference is to use the Go mod tools to download these modules at build time rather than keeping a fork here, which introduces all the additional headaches of keeping it up to date, plus the uncertainty of which version is actually compiled at build time.  In my limited experience, when using go modules in the snap-pe and linux-pe build systems, the version used for compilation is one downloaded by go into GOPATH/pkg/mod folder, not the fork in the vendor folder, and this caused me immense confusion.

**Pull request closed without merging**
