### PR TITLE
golang job matrix, go1.17 compatibility, net update

### PR DESCRIPTION
**Pull request by JanneKiiskila**
This PR is becoming larger and larger:

- Build w multiple golang versions
    - snap uses now 1.15.x and 1.18.x
    - LmPv89 uses v1.17.x
    - Try to be future proof by building with 1.19 and 1.20 as well.
    - Fail the job if it fails to build.
    - Add `go` version to the jobs, so that we can see what version exactly gets used.

- Fix IZUMABL-299 
    - Build fails with golang 1.17 in LmP due to `strings.Cut` which is actually only available with `golang` 1.18 and later.
    - This has now been replaced with a fix that also works on older golangs.

- Update the net module to 0.7.0 to close a dependabot issue.
   - Updated also the `vendor` folder.
   - This updated a few other modules, too. 
   - `go mod tidy` and `go mod vendor` run as well.
   - This means in practice that edge-proxy now needs at least `go` 1.17.
      - Something in `gomega` wants 1.18.
      - `go vet` nags with 1.17 but build succeeds.

### CODE REVIEW

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by jenia81** [comment]
@JanneKiiskila It seems that `go vet` fails, but the test pass
`Run scripts-internal/golang/go_vet_script.sh --all
--all option invoked, will not stop for errors.
Running go vet on ./cmd
Running go vet on ./cmd/edge-proxy
Running go vet on ./http
Running go vet on ./rpc
# github.com/onsi/gomega/internal
Error: ../vendor/github.com/onsi/gomega/internal/polling_signal_error.go:19:33: undefined: any
Error: ../vendor/github.com/onsi/gomega/internal/polling_signal_error.go:[4](https://github.com/PelionIoT/edge-proxy/pull/35/checks#step:9:5)0:14: undefined: any
Error: ../vendor/github.com/onsi/gomega/internal/polling_signal_error.go:[5](https://github.com/PelionIoT/edge-proxy/pull/35/checks#step:9:6)[6](https://github.com/PelionIoT/edge-proxy/pull/35/checks#step:9:7):65: undefined: any
note: module requires Go 1.1[8](https://github.com/PelionIoT/edge-proxy/pull/35/checks#step:9:9)
Running go vet on ./server
Running go vet on ./tls
Skipping ./vendor/*
Done, 5 findings.`

**Comment by jenia81** [comment]
Also, you've mentioned that snap uses 1.15, why don't we test it too?

**Comment by JanneKiiskila** [comment]
Snap uses two different ones, some older ones we do with go 1.15.x, alternative we do with go 1.18.x.
- see `snapcraft.yaml`, [pe-terminal](https://github.com/PelionIoT/snap-pelion-edge/blob/core20/snap/snapcraft.yaml#L548-L577) for example.

**Pull request merged**
