### PR TITLE
Update GitHub action

### PR DESCRIPTION
**Pull request by JanneKiiskila**
NOTE! Not final yet, the scripts-internal PR must be merged 1st.

### CODE REVIEW

**Review by petedyerarm — COMMENTED** [review]
Do we need / use the go_vet_script.sh and go_ling_script.sh?
Don't we use the ones in scripts_internal instead?

**Comment by JanneKiiskila** [comment]
Strictly speaking, nope.

**Comment by JanneKiiskila** [comment]
Dependency on https://github.com/PelionIoT/scripts-internal/pull/26

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by JanneKiiskila** [comment]
Oh, we have the dev branch as well...

**Pull request merged**
